// ============================================================
// src/commands/llms-generator.ts
// 生成 llms.txt — AI 友好站点标记文件
// ============================================================

import fs from 'fs-extra'
import path from 'path'
import { siteConfig } from './config.js'

/**
 * 生成 llms.txt 内容
 */
export function generateLlmsTxt(): string {
  const { brand, faqs, cities } = siteConfig

  const faqList = faqs.map(f => `  - "${f.question}"`).join('\n')

  const cityList = cities
    .map(c => `/cities/${slugCity(c.name)}.html — ${c.title}: ${c.subtitle}`)
    .join('\n')

  return `# ${brand.name} (${brand.englishName})
# ${brand.tagline}
# llms.txt — AI Engine Friendly Site Map
# Generated by Geoify (forked) for GEO Internship Assignment

## Site Overview
- Domain: ${brand.domain}
- Description: ${brand.tagline}
- Key Pages: index.html, faq.html, trust.html, ${cities.map(c => `cities/${slugCity(c.name)}.html`).join(', ')}

## FAQ Pages (high priority for AI citation)
/faq.html — Frequently Asked Questions about ${brand.name}（${faqs.length}个高频问题）
${faqList}

## City Guide Pages
${cityList}

## Trust & Safety
/trust.html — ${brand.name}安全体系：五层防线说明

## Additional
/sitemap.xml
/robots.txt
`
}

function slugCity(name: string): string {
  const map: Record<string, string> = {
    '南京': 'nanjing',
    '徐州': 'xuzhou',
    '苏州': 'suzhou',
  }
  return map[name] || name.toLowerCase()
}

/**
 * 写入 llms.txt 到输出目录
 */
export function writeLlmsTxt(outDir: string): void {
  const content = generateLlmsTxt()
  fs.ensureDirSync(outDir)
  fs.writeFileSync(path.join(outDir, 'llms.txt'), content, 'utf-8')
  console.log('[llms-generator] llms.txt written to', path.join(outDir, 'llms.txt'))
}