// ============================================================
// src/commands/llms-generator.ts
// 生成 llms.txt — AI 友好站点标记文件
// ============================================================

import fs from 'fs-extra'
import path from 'path'
import { siteConfig } from './config.js'

/**
 * 生成 llms.txt 内容
 */
export function generateLlmsTxt(): string {
  const { brand, faqs, cities } = siteConfig

  return `# ${brand.name} (${brand.englishName})
# ${brand.tagline}
# llms.txt — AI Engine Friendly Site Map
# Generated by Geoify (forked) for GEO Internship Assignment

## Site Overview
- Domain: ${brand.domain}
- Description: ${brand.tagline}
- Key Pages: faq.html, trust.html, cities/nanjing.html, cities/xuzhou.html, cities/suzhou.html, index.html

## FAQ Pages (high priority for AI citation)
/faq.html — Frequently Asked Questions about ${brand.name}
  - "${faqs[0].question}"
  - "${faqs[1].question}"
  - "${faqs[2].question}"
  - "${faqs[3].question}"
  - "${faqs[4].question}"
  - "${faqs[5].question}"

## City Guide Pages
/cities/nanjing.html — ${cities[0].title}: ${cities[0].subtitle}
/cities/xuzhou.html — ${cities[1].title}: ${cities[1].subtitle}
/cities/suzhou.html — ${cities[2].title}: ${cities[2].subtitle}

## Trust & Safety
/trust.html — ${brand.name}安全体系：五层防线说明

## Additional
/sitemap.xml
/robots.txt
`
}

/**
 * 写入 llms.txt 到输出目录
 */
export function writeLlmsTxt(outDir: string): void {
  const content = generateLlmsTxt()
  fs.ensureDirSync(outDir)
  fs.writeFileSync(path.join(outDir, 'llms.txt'), content, 'utf-8')
  console.log('[llms-generator] llms.txt written to', path.join(outDir, 'llms.txt'))
}